// Autogenerated - do not edit ->

import '$lib/compute/add_csv_v0.ts';
import '$lib/compute/adder_v0.ts';
import '$lib/compute/argument_extraction_llama.ts';
import '$lib/compute/argument_extraction_v0.ts';
import '$lib/compute/argument_extraction_v1.ts';
import '$lib/compute/audio_v0.ts';
import '$lib/compute/chat_v0.ts';
import '$lib/compute/cluster_extraction_v0.ts';
import '$lib/compute/cluster_extraction_v1.ts';
import '$lib/compute/comment_expander_v0.ts';
import '$lib/compute/count_tokens_v0.ts';
import '$lib/compute/csv_v0.ts';
import '$lib/compute/download_v0.ts';
import '$lib/compute/edit_csv_v0.ts';
import '$lib/compute/feedback_v0.ts';
import '$lib/compute/filter_csv_v0.ts';
import '$lib/compute/gpt_embeddings_v0.ts';
import '$lib/compute/gpt_v0.ts';
import '$lib/compute/grid_v0.ts';
import '$lib/compute/integer_v0.ts';
import '$lib/compute/jq_v0.ts';
import '$lib/compute/jq_v1.ts';
import '$lib/compute/json_v0.ts';
import '$lib/compute/jsonata_v0.ts';
import '$lib/compute/limit_csv_v0.ts';
import '$lib/compute/llama_v0.ts';
import '$lib/compute/markdown_v0.ts';
import '$lib/compute/merge_cluster_extraction_v0.ts';
import '$lib/compute/merge_cluster_extraction_v1.ts';
import '$lib/compute/merge_v0.ts';
import '$lib/compute/multi_audio_v0.ts';
import '$lib/compute/multi_cluster_extraction_v0.ts';
import '$lib/compute/multi_gpt_v0.ts';
import '$lib/compute/multi_whisper_v0.ts';
import '$lib/compute/open_ai_key_v0.ts';
import '$lib/compute/participant_filter_v0.ts';
import '$lib/compute/pinecone_key_v0.ts';
import '$lib/compute/pinecone_v0.ts';
import '$lib/compute/pyodide_v0.ts';
import '$lib/compute/python_v0.ts';
import '$lib/compute/report_v0.ts';
import '$lib/compute/report_v1.ts';
import '$lib/compute/score_argument_relevance_v0.ts';
import '$lib/compute/secret_v0.ts';
import '$lib/compute/stringify_v0.ts';
import '$lib/compute/summarize_v0.ts';
import '$lib/compute/test_v0.ts';
import '$lib/compute/text_to_csv_v0.ts';
import '$lib/compute/text_v0.ts';
import '$lib/compute/translate_v0.ts';
import '$lib/compute/unique_v0.ts';
import '$lib/compute/webpage_v0.ts';
import '$lib/compute/whisper_v0.ts';
import '$lib/compute/whisper_v1.ts';

import add_csv_v0 from '$lib/compute/.plaintext/add_csv_v0.txt?raw';
import adder_v0 from '$lib/compute/.plaintext/adder_v0.txt?raw';
import argument_extraction_llama from '$lib/compute/.plaintext/argument_extraction_llama.txt?raw';
import argument_extraction_v0 from '$lib/compute/.plaintext/argument_extraction_v0.txt?raw';
import argument_extraction_v1 from '$lib/compute/.plaintext/argument_extraction_v1.txt?raw';
import audio_v0 from '$lib/compute/.plaintext/audio_v0.txt?raw';
import chat_v0 from '$lib/compute/.plaintext/chat_v0.txt?raw';
import cluster_extraction_v0 from '$lib/compute/.plaintext/cluster_extraction_v0.txt?raw';
import cluster_extraction_v1 from '$lib/compute/.plaintext/cluster_extraction_v1.txt?raw';
import comment_expander_v0 from '$lib/compute/.plaintext/comment_expander_v0.txt?raw';
import count_tokens_v0 from '$lib/compute/.plaintext/count_tokens_v0.txt?raw';
import csv_v0 from '$lib/compute/.plaintext/csv_v0.txt?raw';
import download_v0 from '$lib/compute/.plaintext/download_v0.txt?raw';
import edit_csv_v0 from '$lib/compute/.plaintext/edit_csv_v0.txt?raw';
import feedback_v0 from '$lib/compute/.plaintext/feedback_v0.txt?raw';
import filter_csv_v0 from '$lib/compute/.plaintext/filter_csv_v0.txt?raw';
import gpt_embeddings_v0 from '$lib/compute/.plaintext/gpt_embeddings_v0.txt?raw';
import gpt_v0 from '$lib/compute/.plaintext/gpt_v0.txt?raw';
import grid_v0 from '$lib/compute/.plaintext/grid_v0.txt?raw';
import integer_v0 from '$lib/compute/.plaintext/integer_v0.txt?raw';
import jq_v0 from '$lib/compute/.plaintext/jq_v0.txt?raw';
import jq_v1 from '$lib/compute/.plaintext/jq_v1.txt?raw';
import json_v0 from '$lib/compute/.plaintext/json_v0.txt?raw';
import jsonata_v0 from '$lib/compute/.plaintext/jsonata_v0.txt?raw';
import limit_csv_v0 from '$lib/compute/.plaintext/limit_csv_v0.txt?raw';
import llama_v0 from '$lib/compute/.plaintext/llama_v0.txt?raw';
import markdown_v0 from '$lib/compute/.plaintext/markdown_v0.txt?raw';
import merge_cluster_extraction_v0 from '$lib/compute/.plaintext/merge_cluster_extraction_v0.txt?raw';
import merge_cluster_extraction_v1 from '$lib/compute/.plaintext/merge_cluster_extraction_v1.txt?raw';
import merge_v0 from '$lib/compute/.plaintext/merge_v0.txt?raw';
import multi_audio_v0 from '$lib/compute/.plaintext/multi_audio_v0.txt?raw';
import multi_cluster_extraction_v0 from '$lib/compute/.plaintext/multi_cluster_extraction_v0.txt?raw';
import multi_gpt_v0 from '$lib/compute/.plaintext/multi_gpt_v0.txt?raw';
import multi_whisper_v0 from '$lib/compute/.plaintext/multi_whisper_v0.txt?raw';
import open_ai_key_v0 from '$lib/compute/.plaintext/open_ai_key_v0.txt?raw';
import participant_filter_v0 from '$lib/compute/.plaintext/participant_filter_v0.txt?raw';
import pinecone_key_v0 from '$lib/compute/.plaintext/pinecone_key_v0.txt?raw';
import pinecone_v0 from '$lib/compute/.plaintext/pinecone_v0.txt?raw';
import pyodide_v0 from '$lib/compute/.plaintext/pyodide_v0.txt?raw';
import python_v0 from '$lib/compute/.plaintext/python_v0.txt?raw';
import report_v0 from '$lib/compute/.plaintext/report_v0.txt?raw';
import report_v1 from '$lib/compute/.plaintext/report_v1.txt?raw';
import score_argument_relevance_v0 from '$lib/compute/.plaintext/score_argument_relevance_v0.txt?raw';
import secret_v0 from '$lib/compute/.plaintext/secret_v0.txt?raw';
import stringify_v0 from '$lib/compute/.plaintext/stringify_v0.txt?raw';
import summarize_v0 from '$lib/compute/.plaintext/summarize_v0.txt?raw';
import test_v0 from '$lib/compute/.plaintext/test_v0.txt?raw';
import text_to_csv_v0 from '$lib/compute/.plaintext/text_to_csv_v0.txt?raw';
import text_v0 from '$lib/compute/.plaintext/text_v0.txt?raw';
import translate_v0 from '$lib/compute/.plaintext/translate_v0.txt?raw';
import unique_v0 from '$lib/compute/.plaintext/unique_v0.txt?raw';
import webpage_v0 from '$lib/compute/.plaintext/webpage_v0.txt?raw';
import whisper_v0 from '$lib/compute/.plaintext/whisper_v0.txt?raw';
import whisper_v1 from '$lib/compute/.plaintext/whisper_v1.txt?raw';

export const code = {
  add_csv_v0,
  adder_v0,
  argument_extraction_llama,
  argument_extraction_v0,
  argument_extraction_v1,
  audio_v0,
  chat_v0,
  cluster_extraction_v0,
  cluster_extraction_v1,
  comment_expander_v0,
  count_tokens_v0,
  csv_v0,
  download_v0,
  edit_csv_v0,
  feedback_v0,
  filter_csv_v0,
  gpt_embeddings_v0,
  gpt_v0,
  grid_v0,
  integer_v0,
  jq_v0,
  jq_v1,
  json_v0,
  jsonata_v0,
  limit_csv_v0,
  llama_v0,
  markdown_v0,
  merge_cluster_extraction_v0,
  merge_cluster_extraction_v1,
  merge_v0,
  multi_audio_v0,
  multi_cluster_extraction_v0,
  multi_gpt_v0,
  multi_whisper_v0,
  open_ai_key_v0,
  participant_filter_v0,
  pinecone_key_v0,
  pinecone_v0,
  pyodide_v0,
  python_v0,
  report_v0,
  report_v1,
  score_argument_relevance_v0,
  secret_v0,
  stringify_v0,
  summarize_v0,
  test_v0,
  text_to_csv_v0,
  text_v0,
  translate_v0,
  unique_v0,
  webpage_v0,
  whisper_v0,
  whisper_v1
};
