#!/usr/bin/env python

# This script simply makes it so src/lib/node_types imports all nodes.
# it also copies the compute files to text files
# so they can get imported as plain text

import os
from glob import glob
from pathlib import Path
import shutil


def build_nodes():

    os.makedirs("src/lib/compute/.plaintext", exist_ok=True)

    marker = "// Autogenerated - do not edit ->"
    computes = sorted(glob("src/lib/compute/*.ts"))
    text = ""
    for f in computes:
        text += f"import '${f[4:]}';\n"

    text += "\n"

    export = "export const code = {\n  <nodes>\n};\n"
    nodes = []

    for f in computes:
        path = Path(f)
        new_directory = path.parent / ".plaintext"
        new_path = new_directory / path.with_suffix(".txt").name
        shutil.copy(path, new_path)
        fn = os.path.splitext(f)[0].split("/")[-1]
        text += f"import {fn} from '${str(new_path)[4:]}?raw';\n"
        nodes.append(fn)

    with open("src/lib/node_types.ts") as r:
        content = r.read()

    content = content.split(marker)[0]
    content += marker + "\n\n"
    content += text + "\n"
    content += export.replace("<nodes>", ",\n  ".join(nodes))

    with open("src/lib/node_types.ts", "w") as w:
        w.write(content)


if __name__ == "__main__":
    build_nodes()
